### ISSUE TITLE
Umwandlung in eine Organization

### ISSUE THREAD

**Issue by ByteDream** [Hartz-Arbeit/LohntDat#14]
Ist eher eine Formalität;
Da das ganze hier ja quasi als Community Projekt anzusehen ist, wäre es praktisch den User @Hartz-Arbeit in eine Organization umzuwandeln. Dadurch sieht man noch leichter, dass es sich hierbei um ein Projekt von mehreren handelt und kann die Features von GH Organizations nutzen, wie z.B. Teams (ka ob das in der Praxis gut einsetzbar ist) oder ggf. mehrere User die das ganze hier Moderieren.

**Comment by Hartz-Arbeit** [comment]
Nach welchen Regeln verteilen wir die Rechte?

**Comment by ByteDream** [comment]
Gute Frage. Vielleicht die Personen, die Inhaltlich viel / am meisten Beitragen

**Comment by ByteDream** [comment]
Wurde umgesetzt
