### ISSUE TITLE
Open Source Lizenz

### ISSUE THREAD

**Issue by ByteDream** [Hartz-Arbeit/LohntDat#16]
Jedes Open Source Projekt sollte eine Lizenz haben, und sei es nur deshalb, um das originale Projekt bei einem Fork erwähnt zu haben.

Ich persönlich würde eine permissive / non-copyleft Lizenz wie MIT oder Apache 2.0 bevorzugen, dadurch ist es anderen (closed-source) Seiten auch möglich ohne große Rechtliche Bedenken dieses Projekt bei sich einzubinden oder ähnliches. 

Meinungen dazu?

**Comment by Eixix** [comment]
+1 für MIT

**Comment by ByteDream** [comment]
Projekt ist nun lizensiert unter [MIT](https://de.wikipedia.org/wiki/MIT-Lizenz) (#19)
