### ISSUE TITLE
Wahl Frontend Framework

### ISSUE THREAD

**Issue by pkunze** [Hartz-Arbeit/LohntDat#2]
Im Unter wurde bereits gefragt, ob Angular, React oder Vue (hier nur in der Reihenfolge aufgrund alphabetischer Sortierung). 

Ich persönlich bin (ohne viel Ahnung von der Materie zu haben) für React. Hauptsächlich weil ich glaube Vue ist zwar geil aber zu Nieschenartig und Angular hat bei mir das letzte mal als ich es versucht habe irgendwie nur Kopfschmerzen verursacht. React fand ich recht leicht zu lernen/scaffolden. Lasse mich aber gern belehren.

**Comment by tsafs** [comment]
Moin, ich wäre auch für React. Liegt daran, dass ich mit Angular früher schlechte Erfahrungen gemacht hab und mit Vue noch gar keine. Passe mich aber gerne an und bin sowieso auch eher im Backend tätig.

**Comment by Sossenbinder** [comment]
+1 für React

**Comment by chescos** [comment]
Würde React nehmen weil damit mehr Leute bereits Erfahrung haben im Gegensatz zu Vue oder Angular, dann gibt's am Ende auch mehr Contributors.

**Comment by maxcodefaster** [comment]
Radikale Idee: Anstatt irgendein legacy framework zu nehmen und 200kb jabba Code auf die clients zu laden einfach bissen HTML, js und CSS. Gerne mit modernem tooling. Es ist nicht mehr 2016 und für ein einfaches Formular plus bisschen Text braucht es nicht ein komplettes Framework und erst Recht keins aus dem letzten Jahrhundert. Bin erschrocken wie viele auch auf Reddit direkt auf den js Framework train springen..

**Comment by kevinunger** [comment]
Scheint so, als müssten wir das demokratisch entscheiden:
https://strawpoll.de/5b5rw8x

**Comment by sp33dlink** [comment]
Ich werfe noch flutter in den Raum. So könnte man mit einer Technologie die Apps (iOS, AOS) und Web lösen. Performant ist es ebenfalls, da nativ.

Da es ja wirklich nur eine Mini-Anwendung ist, ist es auch nicht schlimm, wenn hier noch keine Flutter-Pros vorhanden sind.

**Comment by ByteDream** [comment]
Flutter für Mobile ist eine gute Ide, da stimme ich zu. Allerdings wirds etwas schwierig wenn wir das Projekt auch noch als Web App machen. Flutter Web gibt es zwar, aber die Performance vom ersten Laden der Website ist langsam und die Umsetzung auch etwas fragwürdig (der ganze "DOM" wird in ein Canvas gerendert).

**Comment by thraizz** [comment]
React bietet den Vorteil, dass wir das ganze mit React Native auch easy als App mobil portieren können.

Klar könnte man das ganze auch ohne Framework machen, aber warum? Wenn wir anfangen dann irgendwo mehrseitige Daten mit JS durch die Gegend zu schieben, kommen wir schnell auf die selbe client bundle size 😅

**Comment by Eixix** [comment]
Ich denke grade für die Berechnung und die Möglichkeit alles als eine Cross Plattform App aufzuziehen ist ein Frontend Framework besser als plain :)

**Comment by tsafs** [comment]
Ja, aber die Berechnungen sollten ja alle statisch sein, d.h. die Zahlen vom Gesetzgeber ändern sich nicht so schnell. Wäre schön bequem das alles direkt in JavaScript im Frontend ausrechnen zu lassen.

**Comment by cr4yfish** [comment]
Nach 14h liegt React in der [Umfrage ](https://strawpoll.de/5b5rw8x) mit 12 Stimmen an erster Stelle. 4 Stimmen vor Vue und 6 vor Angular.

Wollen wir React dann als Framework nehmen?

**Comment by kevinunger** [comment]
@cr4yfish Ja, dann lasst uns bis heue 0 Uhr warten. Dann wird es React. Wird sich ja nicht mehr groß verändern. 
Jetzt brauchen wir nur noch eine Abstimmung für ein Metaframework /s. 
Würde sagen wir nehmen einfach default react ohne schnickschnack (oder next.js, wenn das alle wollen).

**Comment by cr4yfish** [comment]
> Würde sagen wir nehmen einfach default react ohne schnickschnack (oder next.js, wenn das alle wollen).

Ich sehe eine weitere Umfrage am Horizont ^^

**Comment by thraizz** [comment]
Ich mag bei NextJS die angenehmen Vorgaben bzgl. Struktur, Ich könnte mir vorstellen dass die Zusammenarbeit damit als Basis cooler ist, weil wir uns nicht auf einen eigenen Stil konzentrieren müssen.

Aber bei der absehbaren Größe könnten wir mit Sicherheit auch ganz normales React nehmen.

**Comment by jpv-os** [comment]
Vorgaben zur Struktur sind für ein kollaboratives Projekt dieser Art meiner Meinung nach unfassbar wichtig. Ich arbeite in der Angular-Welt und lebe im Luxus, dass die Best Practices und etablierten Lösungen für alle Anwendungsfälle jederzeit im Netz bestens dokumentiert sind. 

Wenn es also React-basiert sein soll, empfehle ich daher dringend eine Wahl wie NextJS zu treffen, welches mehr Funktionalität aus der Box heraus liefert und klare Vorgaben bringt. Damit ist das Projekt länger und besser wartbar von mehreren Personen und nicht so stark vom Hauptautoren beeinflusst, der das Projekt initial aufsetzt. Ich stimme dem ersten Punkt von @thraizz voll zu!

**Comment by cr4yfish** [comment]
Da stimme ich euch @thraizz und @jpv-os zu.
Ich mag auch die automatischen performance Optimierungen in Next.js, insbesondere mit Bildern.

Da das weiterhin React ist, sollten wir das ohne Probleme auf den Stack draufpacken können.

Irgendwelche Einwände?

**Comment by kevinunger** [comment]
Bin auch für Next. Macht uns alles einfacherer und wir können mit z.b. den css modules strukturierter arbeiten

**Comment by cr4yfish** [comment]
Dann lasst uns wieder bis heute Abend warten, um allen nochmal die Chance zu geben da ihren Senf zu zu geben.

Bis dahin: Wie stehen hier die Gemüter zu [create-next-app](https://www.npmjs.com/package/create-next-app)?

**Comment by cr4yfish** [comment]
Denke mal das hat sich damit dann erledigt.

**Ergebnis: React mit Next.js.**
