### ISSUE TITLE
Kommunikationskanal außerhalb GitHub?

### ISSUE THREAD

**Issue by thraizz** [Hartz-Arbeit/LohntDat#5]
Die Arbeit am Projekt könnte auch außerhalb GitHub abgesprochen werden, wenn gewünscht - macht es natürlich erstmal schwieriger, alle Entscheidungen transparent zu halten, aber über einen Discord sind Dinge schnell eben geklärt, ob per Text oder im Sprachkanal mit Screensharing etc.

**Comment by sebastianrauer** [comment]
( x ) Discord

**Comment by cr4yfish** [comment]
Hab mal einen [Discord ](https://discord.gg/96JW75uFe7) gemacht.
